### Embedding 

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
## Define the vocabulary size
voc_size=10000

In [9]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4953, 527, 4543, 6632],
 [4953, 527, 4543, 8325],
 [4953, 4697, 4543, 8979],
 [871, 8954, 7787, 3430, 7639],
 [871, 8954, 7787, 3430, 3415],
 [4803, 4953, 409, 4543, 1884],
 [5776, 9548, 420, 3430]]

In [10]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 4953  527 4543 6632]
 [   0    0    0    0 4953  527 4543 8325]
 [   0    0    0    0 4953 4697 4543 8979]
 [   0    0    0  871 8954 7787 3430 7639]
 [   0    0    0  871 8954 7787 3430 3415]
 [   0    0    0 4803 4953  409 4543 1884]
 [   0    0    0    0 5776 9548  420 3430]]


In [13]:
## Feature representation
dim=10

In [18]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 294ms/step


array([[[ 0.04914869,  0.03533262, -0.04843816,  0.029846  ,
         -0.03087621,  0.02675624,  0.03271157,  0.02131495,
          0.01610328,  0.01764121],
        [ 0.04914869,  0.03533262, -0.04843816,  0.029846  ,
         -0.03087621,  0.02675624,  0.03271157,  0.02131495,
          0.01610328,  0.01764121],
        [ 0.04914869,  0.03533262, -0.04843816,  0.029846  ,
         -0.03087621,  0.02675624,  0.03271157,  0.02131495,
          0.01610328,  0.01764121],
        [ 0.04914869,  0.03533262, -0.04843816,  0.029846  ,
         -0.03087621,  0.02675624,  0.03271157,  0.02131495,
          0.01610328,  0.01764121],
        [ 0.0357899 , -0.03899787,  0.04687046, -0.03526301,
         -0.01486922,  0.01404493, -0.04040862,  0.04579863,
         -0.04900011, -0.02870384],
        [-0.00091485,  0.04473269, -0.04021915, -0.02443933,
         -0.0176852 , -0.04675282,  0.0029565 , -0.0260453 ,
          0.00209044, -0.03725034],
        [ 0.01801151,  0.04102664,  0.02636445,  0.0